package nhcm.jvmrtdp.api.jvmti;

import java.util.Locale;

/** All capability bits defined by the Java 8 JVMTI 1.2 header used by JVMRTDP. */
public enum JvmtiCapability {
    CAN_TAG_OBJECTS,
    CAN_GENERATE_FIELD_MODIFICATION_EVENTS,
    CAN_GENERATE_FIELD_ACCESS_EVENTS,
    CAN_GET_BYTECODES,
    CAN_GET_SYNTHETIC_ATTRIBUTE,
    CAN_GET_OWNED_MONITOR_INFO,
    CAN_GET_CURRENT_CONTENDED_MONITOR,
    CAN_GET_MONITOR_INFO,
    CAN_POP_FRAME,
    CAN_REDEFINE_CLASSES,
    CAN_SIGNAL_THREAD,
    CAN_GET_SOURCE_FILE_NAME,
    CAN_GET_LINE_NUMBERS,
    CAN_GET_SOURCE_DEBUG_EXTENSION,
    CAN_ACCESS_LOCAL_VARIABLES,
    CAN_MAINTAIN_ORIGINAL_METHOD_ORDER,
    CAN_GENERATE_SINGLE_STEP_EVENTS,
    CAN_GENERATE_FRAME_POP_EVENTS,
    CAN_GENERATE_BREAKPOINT_EVENTS,
    CAN_SUSPEND,
    CAN_REDEFINE_ANY_CLASS,
    CAN_GET_CURRENT_THREAD_CPU_TIME,
    CAN_GET_THREAD_CPU_TIME,
    CAN_GENERATE_METHOD_ENTRY_EVENTS,
    CAN_GENERATE_METHOD_EXIT_EVENTS,
    CAN_GENERATE_ALL_CLASS_HOOK_EVENTS,
    CAN_GENERATE_COMPILED_METHOD_LOAD_EVENTS,
    CAN_GENERATE_EXCEPTION_EVENTS,
    CAN_GENERATE_MONITOR_EVENTS,
    CAN_GENERATE_VM_OBJECT_ALLOC_EVENTS,
    CAN_GENERATE_NATIVE_METHOD_BIND_EVENTS,
    CAN_GENERATE_GARBAGE_COLLECTION_EVENTS,
    CAN_GENERATE_OBJECT_FREE_EVENTS,
    CAN_FORCE_EARLY_RETURN,
    CAN_GET_OWNED_MONITOR_STACK_DEPTH_INFO,
    CAN_GET_CONSTANT_POOL,
    CAN_SET_NATIVE_METHOD_PREFIX,
    CAN_RETRANSFORM_CLASSES,
    CAN_RETRANSFORM_ANY_CLASS,
    CAN_GENERATE_RESOURCE_EXHAUSTION_HEAP_EVENTS,
    CAN_GENERATE_RESOURCE_EXHAUSTION_THREADS_EVENTS;

    public String wireName() {
        return name().toLowerCase(Locale.ROOT);
    }

    public static JvmtiCapability parse(String value) {
        if (value == null) throw new IllegalArgumentException("Capability name must not be null");
        return valueOf(value.trim().replace('-', '_').toUpperCase(Locale.ROOT));
    }
}
